### PR TITLE
Added Video Camera HW Access

### PR DESCRIPTION
**Pull request by novemberalpha**
I added a line to the devices config that gives the docker container access to the video camera connected to the PI.

### CODE REVIEW

**Comment by gordonbrander** [comment]
This is so timely! Just discovered the same thing this morning http://wiki.openag.media.mit.edu/contributors/gordonb/update_install_self_contained

**Comment by gordonbrander** [comment]
I've added this info to the wiki as well http://wiki.openag.media.mit.edu/docker#exposing_usb_devices

**Comment by novemberalpha** [comment]
That's a really nice writeup. Cool!! 

And thanks!!

**Comment by gordonbrander** [comment]
Thanks! I'm trying to be more consistent about capturing what we learn in the wiki. Any help at this is also much appreciated.

**Pull request merged**
